In [17]:
import numpy as np
sampleArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
sampleArray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr = sampleArray[0, :]

In [20]:
arr

array([1, 2, 3])

In [21]:
sampleArray = np.delete(sampleArray, 1, axis = 1)

In [22]:
sampleArray

array([[1, 3],
       [4, 6],
       [7, 9]])

In [23]:
sampleArray = np.insert(sampleArray, 1,arr, axis=1)

In [24]:
sampleArray

array([[1, 1, 3],
       [4, 2, 6],
       [7, 3, 9]])

In [25]:
sampleArray = np.array([[1, 2,3],[4,5,6],[7,8,9]])

In [28]:
arr = sampleArray[1, :]

In [29]:
arr

array([4, 5, 6])

In [30]:
sampleArray[:,1] = arr

In [31]:
sampleArray

array([[1, 4, 3],
       [4, 5, 6],
       [7, 6, 9]])

In [38]:
sampleArray = np.array([[1, 2, 3],[4,5,6],[7,8,9]])
sampleArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr = sampleArray[:,1]
arr

array([2, 5, 8])

In [33]:
sampleArray = np.delete(sampleArray, 1, axis=1)
sampleArray

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
sampleArray = np.insert(sampleArray, 1, arr, axis=1)